language: node_js
node_js:
- 8.11.1
branches:
  only:
  - master
before_script:
- npm install -g now
- npm i
- npm run build
after_success:
- cp pm2.yml dist/
- cp package.json dist/
- rsync -e 'ssh -o StrictHostKeyChecking=no -i /tmp/deploy_rsa' -ravzup dist/* $FTP_USER@$FPT_HOST:~/podcast-api/
- ssh -oStrictHostKeyChecking=no $FTP_USER@$FPT_HOST sh deploy.sh
before_install:
- openssl aes-256-cbc -K $encrypted_341daef4bf9a_key -iv $encrypted_341daef4bf9a_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa